# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tempural < Formula
  desc "CLI for temporal stuff"
  homepage "https://github.com/weslien/tempural"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/weslien/tempural/releases/download/v0.0.4/tempural_0.0.4_darwin_amd64.tar.gz"
      sha256 "e22c7273ab86f94b991db18b1b644c485b1bd9c6b044ce8cc7cc432ee898360f"

      def install
        bin.install "tempural"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/weslien/tempural/releases/download/v0.0.4/tempural_0.0.4_darwin_arm64.tar.gz"
      sha256 "5d90321c51715e554a291fb7e6500aabe85c06df16e1ebc39983f993c83f651f"

      def install
        bin.install "tempural"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/weslien/tempural/releases/download/v0.0.4/tempural_0.0.4_linux_amd64.tar.gz"
        sha256 "f23b2054b5edb23d60f5c0a0573b9fe7738742e9456cf2279219030a88da6998"

        def install
          bin.install "tempural"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/weslien/tempural/releases/download/v0.0.4/tempural_0.0.4_linux_arm64.tar.gz"
        sha256 "8d28d628fc9877b431cde790bb9b6a33cc3a8c832cc93e19493b76ce91ad6716"

        def install
          bin.install "tempural"
        end
      end
    end
  end

  test do
    system "#{bin}/tempural", "-version"
  end
end
