# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tempural < Formula
  desc "CLI for temporal stuff"
  homepage "https://github.com/weslien/tempural"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/weslien/tempural/releases/download/v0.0.3/tempural_0.0.3_darwin_amd64.tar.gz"
      sha256 "8a54739150d0bdebe22384fef5ab25df5ab246a5f016236dce4c4ef78305dc7e"

      def install
        bin.install "tempural"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/weslien/tempural/releases/download/v0.0.3/tempural_0.0.3_darwin_arm64.tar.gz"
      sha256 "61ce6f842beeb9cf94212198f8addf37b5223237e1db51c261b0b0b4986c0217"

      def install
        bin.install "tempural"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/weslien/tempural/releases/download/v0.0.3/tempural_0.0.3_linux_amd64.tar.gz"
        sha256 "6ec0f65f7617ad1a2ea3aa73e6605475ad8735d278911ef9574587c182e7f3eb"

        def install
          bin.install "tempural"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/weslien/tempural/releases/download/v0.0.3/tempural_0.0.3_linux_arm64.tar.gz"
        sha256 "445a893b2d9b0931c5c6c5195f06c73a5d116fc9e7bc1a47920f6b65023018aa"

        def install
          bin.install "tempural"
        end
      end
    end
  end

  test do
    system "#{bin}/tempural", "-version"
  end
end
